FROM node:lts-alpine as development

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

ARG APP_ENV=local
ENV APP_ENV=${APP_ENV}

EXPOSE 3000

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --legacy-peer-deps

COPY . .

CMD ["npm", "run", "start:debug"]
