version: '3'

services:

  # Base de datos Postgres
  db:
    image: postgres:15
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

  # Backend
  backend:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "80:3000"
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - backend

volumes:
  dbdata:


networks:
  backend:
